apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pvc-es
  namespace: elasticsearch
  
spec:
  storageClassName: ceph-rbd-es
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
