apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv-es
  labels:
    name: ceph-pv-es
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors: 
    - 192.168.4.21:****
    - 192.168.4.22:****
    - 192.168.4.29:****
    path: /k8svolume/pv-es-data1
    user: admin
    secretRef:
      name: ceph-secret-es 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
